development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  # :user_name: this needs to be a valid email
  # :password: this needs to be a valid password for the above email
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  # :user_name: this needs to be a valid email
  # :password: this needs to be a valid password for the above email
  :enable_starttls_auto: true