# t.string   "email",                                                                                                                             null: false
#     t.string   "username"
#     t.string   "phone"
#     t.date     "birth_date"
#     t.string   "skills"
#     t.text     "bio"
#     t.string   "gender"
#     t.string   "city"
#     t.string   "profile_image_url",               default: "http://smallfarms.oregonstate.edu/sites/default/files/_includes/staff_placeholder.jpg"
#     t.string   "needy_rating"
#     t.string   "needed_rating"
#     t.boolean  "trackable"
#     t.string   "task_radius"
#     t.string   "crypted_password"
#     t.string   "salt"
#     t.datetime "created_at"
#     t.datetime "updated_at"
#     t.string   "remember_me_token"
#     t.datetime "remember_me_token_expires_at"
#     t.string   "reset_password_token"
#     t.datetime "reset_password_token_expires_at"
#     t.datetime "reset_password_email_sent_at"
#     t.string   "first_name"
#     t.string   "last_name"