# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Task.create(user_id: 1, needed_id: 2, needy_confirm_completion: nil, needed_confirm_completion: nil, location: 'Vancouver', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam faucibus magna ut bibendum dictum. Donec sed condimentum felis, non imperdiet sem. Nulla magna tortor, ultrices eu dignissim eget, maximus eget lacus. Aenean volutpat porta leo, interdum facilisis nibh tristique vitae. Praesent vitae metus eu arcu luctus aliquam sed ut enim. Aenean quam tellus, finibus id libero ac, vulputate fringilla justo. Donec diam metus, tincidunt et volutpat eu, posuere a odio.', estimated_duration: 120, category: 'test', compensation: 88, difficulty: 'easy', title: 'Test1' )
Task.create(user_id: 2, needed_id: 3, needy_confirm_completion: nil, needed_confirm_completion: nil, location: 'Vancouver', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam faucibus magna ut bibendum dictum. Donec sed condimentum felis, non imperdiet sem. Nulla magna tortor, ultrices eu dignissim eget, maximus eget lacus. Aenean volutpat porta leo, interdum facilisis nibh tristique vitae. Praesent vitae metus eu arcu luctus aliquam sed ut enim. Aenean quam tellus, finibus id libero ac, vulputate fringilla justo. Donec diam metus, tincidunt et volutpat eu, posuere a odio.', estimated_duration: 120, category: 'test', compensation: 88, difficulty: 'easy', title: 'Test1' )
Task.create(user_id: 3, needed_id: 4, needy_confirm_completion: nil, needed_confirm_completion: nil, location: 'Vancouver', description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam faucibus magna ut bibendum dictum. Donec sed condimentum felis, non imperdiet sem. Nulla magna tortor, ultrices eu dignissim eget, maximus eget lacus. Aenean volutpat porta leo, interdum facilisis nibh tristique vitae. Praesent vitae metus eu arcu luctus aliquam sed ut enim. Aenean quam tellus, finibus id libero ac, vulputate fringilla justo. Donec diam metus, tincidunt et volutpat eu, posuere a odio.', estimated_duration: 120, category: 'test', compensation: 88, difficulty: 'easy', title: 'Test1' )