 # t.integer  "user_id"
 #    t.integer  "needed_id"
 #    t.boolean  "needy_confirm_completion"
 #    t.boolean  "needed_confirm_completion"
 #    t.string   "location"
 #    t.text     "description"
 #    t.integer  "estimated_duration"
 #    t.string   "category"
 #    t.datetime "due_date"
 #    t.string   "compensation"
 #    t.string   "image_url",                 default: "http://a3.mzstatic.com/us/r30/Purple3/v4/2f/81/d1/2f81d1ad-bd3c-1bf0-d355-0a843c1f8977/icon128-2x.png"
 #    t.string   "video_url"
 #    t.string   "difficulty"
 #    t.datetime "created_at",                                                                                                                                  null: false
 #    t.datetime "updated_at",                                                                                                                                  null: false
 #    t.string   "title"





# Task.create(user_id: 1, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, location: '1500 West 2nd Avenue, Vancouver, BC', description: 'Hey guys. Im at work and cant get time off to get a coffee downstairs.  Could someone please help me pick up one?  Thanks!', estimated_duration: 10, category: 'coffee', compensation: 5, difficulty: 'easy', title: 'Starbucks Coffee Run!' )
# Task.create(user_id: 1, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, location: '370 Cambie St, Vancouver, BC V6B 2N3', description: 'Really craving a Porchetta but Im really busy. Could anyone in the area help pick me one up?  Cheers!', estimated_duration: 15, category: 'food', compensation: 5, difficulty: 'easy', title: 'Meat & Bread Porchetta Pickup' )
Task.create(user_id: 5, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, location: '3045 W Broadway, Vancouver, BC V6K 2G9', description: 'need someone to pick me up Doggies Delight pet food from Bosleys.  Try get me the 10kg one but if they run out, the 15kg one will suffice for now!', estimated_duration: 'quick', category: 'pet, errand', compensation: '$20 plus cost of food and gas', difficulty: 'easy', title: 'Pick up some dog food for me!', due_date: DateTime.new(11/27/2015) )
# Task.create(user_id: 3, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, location: '2902 West Broadway, Vancouver, BC', description: 'I have to work late and really need someone to pick up my drycleaning before they close. Please help me', estimated_duration: , category: 'errand', compensation: 15, difficulty: 'easy', title: 'Pick up my dry cleaning' )

Task.create!(user_id: 1, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, location: '2902 West Broadway, Vancouver, BC', description: 'I have to work late and really need someone to pick up my drycleaning before they close. Please help me', estimated_duration: 'quick', category: 'errand', compensation: '$50', difficulty: 'easy', title: 'Pick up my dry cleaning', image_url: "http://3.imimg.com/data3/VM/EA/MY-6648931/dry-cleaning-services-250x250.jpg", due_date: DateTime.new(12/12/2015))
Task.create!(user_id: 2, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, title: "Paint my wall", location: '99 Keefer Pl, Vancouver, BC V6B 2L1', description: 'I need someone to come paint a beautiful landscape on my wall while talking soothingly to me.', estimated_duration: 'day_or_two', category: 'painting', compensation: 'I will make you tea and cookies and a $100 gift card to Boston Pizza', difficulty: 'medium', image_url: "http://www.deshow.net/d/file/cartoon/2008-12/bob-ross-landscape-painting-281-28.jpg", due_date: DateTime.new(01/01/2016))
Task.create!(user_id: 5, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, location: '199 Water St, Vancouver, BC V6B 1A7', description: 'We need 12 coffees for out morning office meeting. We are all working on a big presentation and have no time to do it ourselves', estimated_duration: "quick", category: 'errand', compensation: '$30', difficulty: 'easy', title: 'We need coffee', image_url: "http://images.latinoshealth.com/data/images/full/8757/1-2-cups-of-coffee-everyday-prevents-mild-cognitive-impairment.jpg", due_date: DateTime.new(11/26/2015))
Task.create!(user_id: 2, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, title: "Build a replica Enterprise", location: '2948 W 4th Ave, Vancouver, BC', description: 'I am building a scale replicata of the Enterprise out of popsicle sticks. Looking for someone to assist with the building and decoration. Experience with models and art preferred. Fellow Trekkie a must.', estimated_duration: 'epic', category: 'model-building', compensation: '$150, free meals while we work, and the immense satisfaction of achieving the impossible.', difficulty: 'medium', image_url: "http://41.media.tumblr.com/2781523ef130fbde7e081a6caab8ed75/tumblr_nvdhnfdbQv1qzfsnio4_r2_1280.jpg", due_date: DateTime.new(02/14/2016))
Task.create!(user_id: 1, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, title: "Help with Catcher in the Rye", location: '500 West Broadway, 104, Vancouver, BC V5Z 1E9', description: "I've got this huge essay due on this book about some dude who goes to New York. I need someone to maybe jump on a skype call with me and walk me through this.", estimated_duration: 'quick', category: 'homework', compensation: 'I work at Baskin-Robbins and will hook you up with free ice cream for life (or at least as long as I work there, which will be awhile I think).', difficulty: 'hard', image_url: "https://upload.wikimedia.org/wikipedia/en/3/32/Rye_catcher.jpg", due_date: DateTime.new(11/30/2015))
Task.create!(user_id: 4, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, title: "Proofread my reddit posts", location: '850 Powell St, Vancouver, BC V6A 1H8', description: 'I am publishing my autobiography as a series of posts on Reddit. I need someone to go over all my posts for spelling and grammar mistakes before I post them.', estimated_duration: 'day_or_two', category: 'proof-reading', compensation: '$10 per post (I have about 50)', difficulty: 'medium', image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjaw4M-g2lqppRk9Ir7FF9UcSTJdCwiZN2wV0YD1cFxIA0lTc04Q", due_date: DateTime.new(01/01/2016))
Task.create!(user_id: 1, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, title: "Cuddle buddy", location: '5763 Dalhousie Rd, Vancouver, BC V6T 2H9', description: 'I need a cuddle buddy.  Gonna be watching a scary movie', estimated_duration: 'quick', category: 'companion', compensation: 'I will wash you car and stuff', difficulty: 'medium', image_url: "http://queenmobs.com/wp-content/uploads/2015/01/cuddling-dog-cat.jpg", due_date: DateTime.new(12/20/2015))
Task.create!(user_id: 3, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, title: "Film my son's Soccer Game", location: 'Empire Fields, Vancouver, BC', description: "I need someon to film my son's soccer game for his highlight reel. Filming experience greatly needed.", estimated_duration: "quick", category: "filming", compensation: "$150", difficulty: "hard", image_url: "http://s.hswstatic.com/gif/soccer-1.jpg", due_date: DateTime.new(11/22/2015))
Task.create!(user_id: 5, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, location: '128 W Hastings St #300, Vancouver, BC V6B 1G9', description: 'Looking for someone in Lighthouse to help me with some coding stuff.  Im like 100th in queue for assistance', estimated_duration: 'quick', category: 'errand', compensation: 'i will build you a website when im pro', difficulty: 'hard', title: 'Coding help at Lighthouse!', due_date: DateTime.new(11/26/2015) )
Task.create!(user_id: 1, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, title: "Build a fence", location: "31739 King Rd, Abbotsford, BC V2T 5Z2", description: "I need help building a wire fence around my field. Basic carpentry expereince preferred", estimated_duration: "epic", category: "construction", compensation: "$500", difficulty: "hard", image_url: "http://www.deckmastersnw.com/wp-content/uploads/DSC01303-e1314409126905.jpg", due_date: DateTime.new(12/31/2015))
Task.create!(user_id: 4, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, title: "Pick up my dogs poop", location: "west 4th, Vancouver, BC", description: "I need someone to walk 50 feet behind me an pick up my dogs poop", estimated_duration: "day_or_two", category: 'pooper scooper', compensation: "A whole bunch of A&W coupons!", difficulty: "medium", image_url: "http://www.wehoville.com/wp-content/uploads/2014/09/Dog-Poop.png", due_date: DateTime.new(12/25/2015))
Task.create!(user_id: 3, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, title: "Help I'm trapped", location: "gastown, Vancuover, BC", description: "I really need help getting through this. I went through a wall of bricks and found a secret warp zone! But alas, something seems to have gone wrong. I am stuck in the same level for what appears to be eternity. Or until I perish, which ever comes first. I go through the pipe at the end of the level, only to come out the other side at the beginning of the same level! How this has come to be is still a mystery to me. One that I perhaps do not wish to solve. For with the answers I am certain bigger questions will arise. If you perhaps have any insight into my unfortunate circumstance I fear I would be unable to refuse your assistance in helping me find some answers to this eternal, damned, riddle. Otherwise I fear the end is near. My legs tire, my head aches. Jumping on these deranged turtle creatures while avaiding all these sea monsters is beginning to break my spirit. At least I am somehow impervious to drowning. A small victory in an otherwise empty existence. I do not know what I did to deserve this horrible fate. It's a shame really. There was so much I wanted to do before my time was up.... I always wanted to go to Italy", estimated_duration: "epic", category: 'existential', compensation: "Free plumbing for life", difficulty: "hard", image_url: "http://themushroomkingdom.net/images/bugs/smb_minus_world_6.png", video_url: "https://www.youtube.com/embed/5WYGElEqoHc", due_date: DateTime.new(12/25/2015))
Task.create!(user_id: 5, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, title: "Help me harvest my garden", location: "759 Malkin Ave, Vancouver, BC", description: "I am getting a bit on in years and need someone to help me in the garden. Cant do all the bending down and whatnot. Its about a days worth of work in a nice beautiful community garden.", estimated_duration: "day_or_two", category: 'gardening', compensation: "$50 and as many vegetables as you can carry", difficulty: "medium", image_url: "http://images.glaciermedia.ca/polopoly_fs/1.1071670.1400793280!/fileImage/httpImage/image.jpg_gen/derivatives/landscape_563/garden.jpg", due_date: DateTime.new(04/16/2015))
Task.create!(user_id: 4, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, title: "Help me find my brother", location: "fraser st, Vancouver, BC", description: "My brother mario is missing. We were out on a job a few days ago and he climbed into this giant weird looking pipe. Three was a weird sound and he was gone. He hasn't been seen since. Please help me find him.", estimated_duration: "epic", category: 'rescue', compensation: "$1000", difficulty: "hard", image_url: "http://www.best-games-directory.com/uploads/3/8/3/2/3832861/5277731_orig.png", due_date: DateTime.new(12/25/2015))
Task.create!(user_id: 6, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, title: "Bring fans to the show", location: "west 4th, Vancouver, BC", description: "We need an experienced bus driver to take a group of fans to the concert.", estimated_duration: "quick", category: 'driving', compensation: "$200 and a ticket to the show", difficulty: "medium", image_url: "http://i61.photobucket.com/albums/h80/lococj7/bus/7206066e.jpg", due_date: DateTime.new(12/25/2015))
Task.create!(user_id: 6, needed_id: nil, needy_confirm_completion: false, needed_confirm_completion: false, title: "Learn the dance moves", location: "west 4th, Vancouver, BC", description: "I need someone to learn my dance routines immediately for a few conerts. We had an injury and need a replacement NOW.", estimated_duration: "epic", category: 'dancing', compensation: "Will discuss via chat. A potential salary or contract upon meeting", difficulty: "hard", image_url: "http://cdn.betches.com/sites/default/files/article/list/images/125144-netherlands-us-music-beyonce.jpg", video_url: "https://www.youtube.com/embed/kGQSQJjAYag", due_date: DateTime.new(12/25/2015))